version: '3'
services:
  speedtest:
    container_name: speedtest
    build: https://github.com/PapaBravo/speedtest-docker.git
    deploy:
      restart_policy: 
          condition: on-failure 
    ports: 
    - "3000:3000"